# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jupyter_probe.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'jupyter_probe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13jupyter_probe.proto\"\x1b\n\x08Message1\x12\x0f\n\x07to_send\x18\x01 \x02(\t\";\n\x10Message1andahalf\x12\x0b\n\x03num\x18\x01 \x02(\x05\x12\x0c\n\x04num1\x18\x02 \x02(\x05\x12\x0c\n\x04num2\x18\x03 \x02(\x05\"<\n\x08Message2\x12\x0f\n\x07to_send\x18\x01 \x02(\t\x12\x1f\n\x04type\x18\x02 \x02(\x0b\x32\x11.Message1andahalf\"=\n\x08Message3\x12\x18\n\x10\x65ngine_burn_time\x18\x01 \x02(\x02\x12\x17\n\x0f\x61ngle_of_thrust\x18\x02 \x02(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jupyter_probe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE1']._serialized_start=23
  _globals['_MESSAGE1']._serialized_end=50
  _globals['_MESSAGE1ANDAHALF']._serialized_start=52
  _globals['_MESSAGE1ANDAHALF']._serialized_end=111
  _globals['_MESSAGE2']._serialized_start=113
  _globals['_MESSAGE2']._serialized_end=173
  _globals['_MESSAGE3']._serialized_start=175
  _globals['_MESSAGE3']._serialized_end=236
# @@protoc_insertion_point(module_scope)
