# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: warm_up.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'warm_up.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwarm_up.proto\"+\n\x04\x46ish\x12\x0f\n\x07species\x18\x01 \x02(\t\x12\x12\n\nsize_in_cm\x18\x02 \x01(\x05\"!\n\x08\x41quarium\x12\x15\n\x06\x66ishes\x18\x01 \x03(\x0b\x32\x05.Fish')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warm_up_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FISH']._serialized_start=17
  _globals['_FISH']._serialized_end=60
  _globals['_AQUARIUM']._serialized_start=62
  _globals['_AQUARIUM']._serialized_end=95
# @@protoc_insertion_point(module_scope)
